version: '3.8'

services:
  http-search-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: http-search-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
      - "4200:4200"  # Angular dev server
    environment:
      - NODE_ENV=development
      - PFX_PATH=/app/certs/localhost.p12
      - SSL_PASSPHRASE=dev123
    volumes:
      # Mount source code for development
      - .:/app
      - /app/node_modules
      # Mount certificate directory
      - ./certs:/app/certs:ro
    networks:
      - http-search-network
    command: ["npm", "run", "start"]

networks:
  http-search-network:
    driver: bridge